image:
  name: harbor.wariie.cloud/library/standard-app:90a1a2d64f4d8e4ad423618b3f2431a6c8de5378
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
crossplane:
  enabled: false
  # composition ou direct

  type: composition
ingress:
  enabled: true
  host: standard-app.wariie.cloud
