image:
  name: harbor.wariie.cloud/library/standard-app:cd140339394c542c11a4adb482753a9bdb5b8669
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
crossplane:
  enabled: false
  # composition ou direct

  type: composition
ingress:
  enabled: true
  host: standard-app.wariie.cloud
