image:
  name: harbor.cgicloudtoulouse.fr/library/standard-app:8611711bbc885cf4dd302e70e6408794da01af6d
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
crossplane:
  enabled: false
  # composition ou direct

  type: composition
ingress:
  enabled: false
  host: standard-app.wariie.cloud
