apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clean-release-name" .  }}-deployment
  labels:
    app: {{ include "clean-release-name" .  }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "clean-release-name" .  }}
  template:
    
    metadata:
      labels:
        app: {{ include "clean-release-name" .  }}
    spec:
        {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ include "clean-release-name" .  }}
        image: {{ .Values.image.name }}
        ports:
        - containerPort: 5000
        env:
          - name: DB_HOST
            value: {{ include "clean-release-name" .  }}-postgres
          - name: DB_PORT
            value: 5432
          - name: DB_USER
            valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
          - name: DB_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          - name: DB_NAME
            value: librairie_db
          - name: PORT
            value: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000