apiVersion: v1
kind: Service
metadata:
  name: {{ include "clean-release-name" .  }}-svc
spec:
  selector:
    app: {{ include "clean-release-name" .  }}
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP