standard-app:
  enabled: true
  image:
    name: harbor.wariie.cloud/library/standard-app-postgres:ba1ebe2e681a4f30cea69944e5084a08f90428a1
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
  crossplane:
    enabled: false
    # composition ou direct

    type: composition
  ingress:
    enabled: true
    host: standard-app.wariie.cloud

standard-app-postgres:
  enabled: false

postgres:
  enabled: false
