standard-app-postgres:
  enabled: true
  # image:
  #   name: harbor.wariie.cloud/library/standard-app-postgres:ba1ebe2e681a4f30cea69944e5084a08f90428a1
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
  crossplane:
    enabled: true
    # composition ou direct
    type: composition
  ingress:
    enabled: true
    host: standard-app.wariie.cloud

postgres:
  enabled: true

standard-app:
  enabled: false