image:
  name: harbor.wariie.cloud/library/standard-app-postgres:9d0b058fb797fb7f413e20a4b9d6d87559df52ba
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
crossplane:
  enabled: false
  # composition ou direct

  type: composition
ingress:
  enabled: true
  host: standard-app.wariie.cloud
