image:
  name: harbor.cgicloudtoulouse.fr/library/standard-app-postgres:ea0ebeb93f5405a4d49e82b85e60f1adb9f76eba
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
crossplane:
  enabled: false
  # composition ou direct

  type: composition
ingress:
  enabled: true
  host: standard-app.wariie.cloud
