image:
  name: harbor.cgicloudtoulouse.fr/library/standard-app-postgres:746c3398a191d3dc0728dd9524ec35c3f976fd25
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
crossplane:
  enabled: false
  # composition ou direct

  type: composition
ingress:
  enabled: true
  host: standard-app.wariie.cloud
