image:
  name: harbor.cgicloudtoulouse.fr/library/standard-app-postgres:a40a3ffa7cb8ad3db4ecdf46fb94815b5270be74
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
crossplane:
  enabled: false
  # composition ou direct

  type: composition
ingress:
  enabled: true
  host: standard-app.wariie.cloud
