apiVersion: v1
kind: Service
metadata:
  name: {{ include "clean-release-name" .  }}-postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432